### ISSUE TITLE
Green Bay Packers

### ISSUE THREAD

**Issue by Zero2Cool** [teamcolors/teamcolors.github.io#44]
The Packers official colors are Dark Green (PMS 5535-C), Gold (PMS 1235-C) and White. 

Gold (PMS 1235-C)  would be #ffb81c  or (websafe #ffcc33)
Dark Green (PMS 5535-C) would be #183028 or (websafe #003333)

:-) 

Source: http://www.packers.com/fan-zone/faq.html

**Comment by jimniels** [comment]
Thanks for the tip.

Team colors have been updated recently (for the NFL and NBA) to include PMS and CMYK colors based on specifications from the respective leagues.

That means the Green Bay Packers now have the PMS colors you specified. But rather than a programatic conversion between print and screen colors, I've used the [specified team colors from the NFL](https://github.com/teamcolors/teamcolors.github.io#official-color-references).

Here's a preview of the Green Bay logo slick provided by the NFL:

![screen shot 2015-06-16 at 5 10 35 pm](https://cloud.githubusercontent.com/assets/1316441/8196609/a34f543c-144a-11e5-9324-fd4a8440d4e3.png)

Closing this issue.
