### ISSUE TITLE
NBA Hex

### ISSUE THREAD

**Issue by gavinr** [teamcolors/teamcolors.github.io#62]
NBA data set does not have HEX. For consistency I think it should have that. Thanks!

**Comment by jimniels** [comment]
See [the README notes on the NBA colors](https://github.com/teamcolors/teamcolors.github.io#nba).

Basically the reason HEX colors are not in the original data set is because they are not provided by the NBA in their official logo slicks. So, if/when they become officially provided, I just do a RGB -> HEX programmatic conversion, then I don't have keep track of two sets if something changes.

**Comment by gavinr** [comment]
Ah, I see. Thanks for the clarification.
